### ISSUE TITLE
1.0.0 doesn't use `genesis.bosh-dns` runtime config

### ISSUE THREAD

**Issue by michaelmccaskill** [genesis-community/cf-app-autoscaler-genesis-kit#6]
I have a non-proto director (2.0.1 kit) that has set the `genesis.bosh-dns` runtime config. However, this kit doesn't use it and subsequently bombs due bosh-dns missing from the `default` runtime config.

```
 Errors were found in your runtime-config:
    - BOSH DNS is not in the runtime-config, which is required. Refer to
      'genesis man lab-sandbox' for more info.

  runtime config [FAILED]
```

It seems like this kit should be updated to support this usage of the separate runtime config.

**Comment by itsouvalas** [comment]
issue fixed - [pr merged](https://github.com/genesis-community/cf-app-autoscaler-genesis-kit/commit/4e901bf31156256b98f7cb5d3f306c128a3172b8)
